version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_BASE_URL=http://backend:5000/api
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  admin:
    build:
      context: ./admin
      args:
        - VITE_API_BASE_URL=http://backend:5000/api
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge