services:
  - type: web
    name: vismartcarhire
    env: static
    buildCommand: cd frontend && npm ci && npx --yes vite build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html